### ISSUE TITLE
Test: 20 Projects

### ISSUE THREAD

**Issue by subwaystation** [qbicsoftware/project-manager-portlet#8]
Please provide a screenshot about how it looks like when a user follows 20 projects. Is this still feasible?

**Comment by spaethju** [comment]
![bildschirmfoto 2018-06-22 um 10 43 24](https://user-images.githubusercontent.com/12552184/41767220-5b79231c-7609-11e8-8984-40ad080aabac.png)

so this is the chart containing 13 projects, i think more than 15 will be an overload. How likely is it that you follow more than 15 projects at the same time? @subwaystation
